### PR TITLE
Collaboration friendliness

### PR DESCRIPTION
**Pull request by Dual-Iron**
See #65 
Moved base branch from master to region-packs.

### CODE REVIEW

**Comment by Garrakx** [comment]
First, thank you for your contribution. I wanted to fix the references for the longest time by I just kept delaying it. 
I prefer to add the references in a slighty different way, no real reason just personal preferences. Furthermore, I prefer not to include any libraries in the repository as well. I expect people that contribute to this repo are familiar with RW modding so more in-depth instructions should be found in the modding wiki for example.
Anyway, thank you again 😊

**Comment by Dual-Iron** [comment]
> First, thank you for your contribution. I wanted to fix the references for the longest time by I just kept delaying it.
> I prefer to add the references in a slighty different way, no real reason just personal preferences. Furthermore, I prefer not to include any libraries in the repository as well. I expect people that contribute to this repo are familiar with RW modding so more in-depth instructions should be found in the modding wiki for example.
> Anyway, thank you again 😊

I'm confused, are you requesting changes or denying the PR?

**Comment by Garrakx** [comment]
Explaining why I closed the PR.

**Comment by Dual-Iron** [comment]
Alright. I'll delete the branch if there are no plans to merge this PR.

**Pull request closed without merging**
